import type {
  CommodityNodeBenchmarkContract,
  CommodityNodeDataSource,
} from './commoditynode-data-contracts';

const REVIEWED_AT = '2026-07-28T00:00:00Z';
const REVIEWER = 'CommodityNode Data Governance';

export const COMMODITYNODE_DATA_SOURCES = [
  {
    id: 'yahoo-finance',
    name: 'Yahoo Finance',
    publisher: 'Yahoo Finance LLC',
    category: 'market_quote',
    homepageUrl: 'https://finance.yahoo.com/',
    accessUrl: 'https://finance.yahoo.com/markets/commodities/',
    cadence: 'intraday',
    transport: 'html',
    attribution: 'Yahoo Finance',
    editorialOwner: 'CommodityNode Markets',
    operationalOwner: 'CommodityNode Data Platform',
    rights: {
      status: 'review_required',
      license: null,
      termsUrl: 'https://legal.yahoo.com/us/en/yahoo/terms/otos/index.html',
      reviewedAt: REVIEWED_AT,
      reviewedBy: REVIEWER,
      expiresAt: null,
      publicDisplay: false,
      redistribution: false,
      derivativeWorks: false,
      commercialUse: false,
      attributionRequired: true,
      restrictions: [
        'Automated collection requires express prior permission under the reviewed terms.',
        'Do not create a competing or materially substitutive data feed, database, widget, or service.',
        'Obtain a licensed market-data provider agreement before public quote redistribution.',
      ],
      thirdPartyCaveat: 'Displayed market data may be supplied by third-party exchanges or data vendors.',
    },
  },
  {
    id: 'usgs-nmic',
    name: 'USGS National Minerals Information Center',
    publisher: 'U.S. Geological Survey',
    category: 'official_statistics',
    homepageUrl: 'https://www.usgs.gov/centers/national-minerals-information-center',
    accessUrl: 'https://www.usgs.gov/centers/national-minerals-information-center/commodity-statistics-and-information',
    cadence: 'annual',
    transport: 'download',
    attribution: 'Source: U.S. Geological Survey',
    editorialOwner: 'CommodityNode Research',
    operationalOwner: 'CommodityNode Data Platform',
    rights: {
      status: 'approved',
      license: 'U.S. public domain',
      termsUrl: 'https://www.usgs.gov/faqs/are-usgs-reportspublications-copyrighted',
      reviewedAt: REVIEWED_AT,
      reviewedBy: REVIEWER,
      expiresAt: null,
      publicDisplay: true,
      redistribution: true,
      derivativeWorks: true,
      commercialUse: true,
      attributionRequired: true,
      restrictions: [
        'Inspect each record for separately marked third-party photographs, illustrations, or graphics.',
        'Do not use USGS marks in a way that implies endorsement.',
      ],
      thirdPartyCaveat: 'Some non-USGS media embedded on USGS pages can remain separately copyrighted.',
    },
  },
  {
    id: 'eia',
    name: 'U.S. Energy Information Administration',
    publisher: 'U.S. Energy Information Administration',
    category: 'official_statistics',
    homepageUrl: 'https://www.eia.gov/',
    accessUrl: 'https://www.eia.gov/opendata/',
    cadence: 'weekly',
    transport: 'api',
    attribution: 'Source: U.S. Energy Information Administration, with publication date',
    editorialOwner: 'CommodityNode Research',
    operationalOwner: 'CommodityNode Data Platform',
    rights: {
      status: 'approved',
      license: 'U.S. public domain',
      termsUrl: 'https://www.eia.gov/about/copyrights_reuse.php',
      reviewedAt: REVIEWED_AT,
      reviewedBy: REVIEWER,
      expiresAt: null,
      publicDisplay: true,
      redistribution: true,
      derivativeWorks: true,
      commercialUse: true,
      attributionRequired: true,
      restrictions: [
        'Include an acknowledgment and the publication date.',
        'Do not reproduce protected third-party photographs or licensed materials without permission.',
        'Do not use the EIA logo without express consent.',
      ],
      thirdPartyCaveat: 'Protected third-party materials and photographs are excluded from the public-domain grant.',
    },
  },
  {
    id: 'faostat',
    name: 'FAOSTAT',
    publisher: 'Food and Agriculture Organization of the United Nations',
    category: 'official_statistics',
    homepageUrl: 'https://www.fao.org/faostat/en/',
    accessUrl: 'https://www.fao.org/faostat/en/#data',
    cadence: 'annual',
    transport: 'download',
    attribution: 'FAO. [year]. FAOSTAT: [dataset]. Accessed [date]. Licence: CC BY 4.0.',
    editorialOwner: 'CommodityNode Research',
    operationalOwner: 'CommodityNode Data Platform',
    rights: {
      status: 'approved',
      license: 'CC BY 4.0 with FAO Statistical Database Terms of Use',
      termsUrl: 'https://www.fao.org/contact-us/terms/db-terms-of-use/en/',
      reviewedAt: REVIEWED_AT,
      reviewedBy: REVIEWER,
      expiresAt: null,
      publicDisplay: true,
      redistribution: true,
      derivativeWorks: true,
      commercialUse: true,
      attributionRequired: true,
      restrictions: [
        'Verify dataset-level metadata for third-party exceptions before ingestion.',
        'Use the prescribed FAO citation format.',
        'Do not imply FAO endorsement or use FAO data to promote a specific enterprise or product.',
      ],
      thirdPartyCaveat: 'Dataset metadata can impose different terms for third-party-contributed data.',
    },
  },
] as const satisfies readonly CommodityNodeDataSource[];

export const COMMODITYNODE_BENCHMARKS = [
  {
    id: 'copper-comex-hg',
    commodityId: 'copper',
    name: 'COMEX Copper futures',
    providerSymbol: 'HG=F',
    instrumentType: 'futures_benchmark',
    exchange: 'COMEX',
    currency: 'USD',
    unit: 'USD/lb',
    sourceId: 'yahoo-finance',
    delayPolicy: 'Provider-defined and not guaranteed; display an explicit as-of timestamp when licensed.',
    proxySemantics: 'A futures benchmark used as a financial-market proxy for copper, not a physical spot assessment.',
    caveat: 'The contract does not represent every regional cathode premium, concentrate treatment charge, or local physical price.',
    publicDisplayRequiresRightsApproval: true,
  },
  {
    id: 'crude-oil-nymex-wti',
    commodityId: 'crude-oil',
    name: 'NYMEX WTI Crude Oil futures',
    providerSymbol: 'CL=F',
    instrumentType: 'futures_benchmark',
    exchange: 'NYMEX',
    currency: 'USD',
    unit: 'USD/barrel',
    sourceId: 'yahoo-finance',
    delayPolicy: 'Provider-defined and not guaranteed; display an explicit as-of timestamp when licensed.',
    proxySemantics: 'A WTI futures benchmark, not a universal physical crude-oil price.',
    caveat: 'WTI is not interchangeable with Brent, Dubai/Oman, or individual physical grades and differentials.',
    publicDisplayRequiresRightsApproval: true,
  },
  {
    id: 'gold-comex-gc',
    commodityId: 'gold',
    name: 'COMEX Gold futures',
    providerSymbol: 'GC=F',
    instrumentType: 'futures_benchmark',
    exchange: 'COMEX',
    currency: 'USD',
    unit: 'USD/troy ounce',
    sourceId: 'yahoo-finance',
    delayPolicy: 'Provider-defined and not guaranteed; display an explicit as-of timestamp when licensed.',
    proxySemantics: 'A futures benchmark used as a financial-market proxy for gold.',
    caveat: 'The contract does not establish local physical premiums, vault availability, or retail dealer pricing.',
    publicDisplayRequiresRightsApproval: true,
  },
  {
    id: 'cocoa-ice-us-cc',
    commodityId: 'cocoa',
    name: 'ICE U.S. Cocoa futures',
    providerSymbol: 'CC=F',
    instrumentType: 'futures_benchmark',
    exchange: 'ICE Futures U.S.',
    currency: 'USD',
    unit: 'USD/metric ton',
    sourceId: 'yahoo-finance',
    delayPolicy: 'Provider-defined and not guaranteed; display an explicit as-of timestamp when licensed.',
    proxySemantics: 'A deliverable futures benchmark, not a universal farm-gate or origin-differential price.',
    caveat: 'The contract does not represent every origin differential, quality adjustment, or local producer price.',
    publicDisplayRequiresRightsApproval: true,
  },
] as const satisfies readonly CommodityNodeBenchmarkContract[];
